services:
  egm-jacksorbetter:
    build:
        context: .
        dockerfile: Dockerfile
    image: tykhegaming/egm-jacksorbetter-game-service:latest
    container_name: egm-jacksorbetter-game-service
    networks:
     - gaming-network
    ports:
      - "9080:9080"
    restart: unless-stopped


networks:
  gaming-network:
    external: true
    name: gaming-network
